// quiz/src/app/components/nav.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
    selector: "app-nav",
    template: `<div>
        <button
            *ngFor="let option of options; let i = index"
            [ngClass]="{ selected: i === selection }"
            (click)="onSelection.emit(i)"
            >
            {{ option }}
        </button>
    </div>`,
    styles: [
        `
    div {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        margin-bottom: 20px;
    }

    button {
        padding: 5px;
    }

    .selected {
        font-weight: bold;
        background-color: #aaa;
    }
    `
    ]
})
export class NavComponent {
    @Input() options!: string[];
    @Input() selection?: number;
    @Output() onSelection = new EventEmitter<number>();
}

// quiz/src/components/Tab/Nav.vue
<template>
    <div class="nav-menu">
        <button v-for="(option, index) in options" :key="option"
        :class="{ selected: index === selection }"
        @click="$emit('onSelection', index)">
        {{ option }}
        </button>
    </div>
</template>

<script setup lang="ts">
    export interface NavProps {
        options: string[] 
        selection?: number 
    }

    export interface NavEvents {
        (e: 'onSelection', val: number): void 
    }

    defineProps<NavProps>()
    defineEmits<NavEvents>()
</script>

<style scoped>    
.nav-menu {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    margin-bottom: 20px;
}

button {
    margin-right: 10px;
    padding: 5px;
}

.selected {
    margin-right: 10px;
    font-weight: bold;
    background-color: #aaa;
}
</style>
