// quiz/src/components/Tab/Tab.vue
<template>
    <div>
        <Nav
            :options="buttonsOptions"
            :selection="currentButton"
            @on-selection="select"
        />
        <Panel
            :text="texts[currentButton]"
        />
    </div>
</template>


<script setup lang="ts">
import { ref } from 'vue'
import Panel, { type PanelProps } from './Panel.vue'
import Nav, { type NavProps} from './Nav.vue'

const buttonsOptions: NavProps = ["Tab1", "Tab2", "Tab3", "Tab4"]
const texts = ["Texto da Tab1", "Texto da Tab2", "Texto da Tab3", "Texto da Tab4"]

const currentButton =  ref(0)

function select(buttonIndex: number) {
    currentButton.value = buttonIndex
}

</script>

<style scoped>    
    div {
        margin: 50px;
    }
</style>

// quiz/src/components/Tab/Tab.tsx
import React, { useState } from 'react';

import { Nav } from './Nav';
import { Panel } from './Panel';
import './Tab.css';

export function Tab() {
    const buttonsOptions = [
        {
            options: ["Tab1", "Tab2", "Tab3", "Tab4"],
            texts: ["Texto do Tab1",
                "Texto do Tab2",
                "Texto do Tab3",
                "Texto do Tab4"]
        }
    ];

    const [currentTab, setTab] = useState(0);
    const handleCurrentTab = (tabIndex: number) => {
        setTab(tabIndex);
    }

    return (
        <div className="tab">
            <Nav options={ buttonsOptions[0].options } currentTab={currentTab} handleSetTab={ handleCurrentTab } />
            <Panel text={ buttonsOptions[0].texts[currentTab] } />
        </div>
    );
}
