// quiz/src/components/Tab/Panel.vue
<template>
    <div>
        <h2>{{text}}</h2>
    </div>
</template>

<script setup lang="ts">
    export interface PanelProps {
        text: string
    }

    defineProps<PanelProps>()
</script>

<style scoped>    
    div {
        text-align: center;
        border: 2px solid black;
        border-radius: 5px;
        padding: 50px 20px;
      }
</style>

// quiz/src/app/components/panel.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-panel",
  template: `<div>{{ text }}</div>`,
  styles: [
    `
      div {
        text-align: center;
        border: 2px solid black;
        border-radius: 5px;
        padding: 50px 0;
      }
    `
  ]
})
export class PanelComponent {
  @Input() text?: string;
}
